services:
  - type: web
    name: task-manager-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString

  - type: static_site
    name: task-manager-frontend
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: task-manager-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: task-manager-db
    plan: free

