services:
  - type: web
    name: task-manager-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString

databases:
  - name: task-manager-db
    plan: free
